### ISSUE TITLE
But if I want to train my own model? How i can do that?

### ISSUE THREAD

**Issue by Whhhatttt** [TairYerniyazov/SimpleLanguageModel#1]

**Comment by TairYerniyazov** [comment]
Thanks for your feedback! You can use the "train" method after instantiating the WordRNN class. This method allows you to specify the datasets you want to use for training, as well as the number of epochs:

```python
language_model.train([
    'your_book_1.txt',
    'your_book_2.txt',
    'your_book_3.txt',
    # Add more datasets as needed
], save_path, n_epochs=100)
```

Additionally, you can specify the number of words to consider in the dictionary used by the word embedding layer, as well as the length of the input prompt. For example:

```python
language_model = WordRNN(10_000, 5)
language_model.compile_model()
```

I have not included options for fine-tuning the architecture because attempting to replicate the entire TF API initially designed for such purposes would be impractical.

Please note that the LSTM units used by the model cannot be efficiently accelerated via cuDNN since they do not meet all the requirements mentioned on the Keras Library website (https://keras.io/api/layers/recurrent_layers/lstm/).

Training on 1-2 books with a mid-range Core i5 processor will take approximately an hour.
